### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by jjn037** [ebetica/autogradpp#23]
/home/d09/workspace/jjn/autogradpp/test.cpp: In function ‘std::map<std::basic_string<char>, std::function<void()> > construct_tests()’:
/home/d09/workspace/jjn/autogradpp/test.cpp:523:12: error: parameter declared ‘auto’
      auto& model, auto& forward_op, auto& optim) {
            ^
/home/d09/workspace/jjn/autogradpp/test.cpp:523:25: error: parameter declared ‘auto’
      auto& model, auto& forward_op, auto& optim) {
                         ^
/home/d09/workspace/jjn/autogradpp/test.cpp:523:43: error: parameter declared ‘auto’
      auto& model, auto& forward_op, auto& optim) {
                                           ^
/home/d09/workspace/jjn/autogradpp/test.cpp: In lambda function:
/home/d09/workspace/jjn/autogradpp/test.cpp:592:6: error: ‘model’ was not declared in this scope
      model->cuda();
      ^
/home/d09/workspace/jjn/autogradpp/test.cpp:609:40: error: ‘forward_op’ was not declared in this scope
        Variable x = forward_op(Var(inp));
                                        ^
/home/d09/workspace/jjn/autogradpp/test.cpp:613:8: error: ‘optim’ was not declared in this scope
        optim->zero_grad();
        ^
/home/d09/workspace/jjn/autogradpp/test.cpp:620:59: error: ‘forward_op’ was not declared in this scope
    auto result = std::get<1>(forward_op(Var(tedata, false)).max(1));
                                                           ^
/home/d09/workspace/jjn/autogradpp/test.cpp: In lambda function:
/home/d09/workspace/jjn/autogradpp/test.cpp:656:29: error: no match for call to ‘(const construct_tests()::__lambda41) (int, int, bool, std::shared_ptr<autograd::SimpleContainer>&, construct_tests()::__lambda44::__lambda45&, std::shared_ptr<autograd::SGD>&)’
        model, forward, optim);
                             ^
/home/d09/workspace/jjn/autogradpp/test.cpp:521:21: note: candidates are:
  auto test_mnist = [](
                     ^
/home/d09/workspace/jjn/autogradpp/test.cpp:656:29: note: void (*)(uint32_t, uint32_t, bool) {aka void (*)(unsigned int, unsigned int, bool)} <conversion>
        model, forward, optim);
                             ^
/home/d09/workspace/jjn/autogradpp/test.cpp:656:29: note:   candidate expects 4 arguments, 7 provided
/home/d09/workspace/jjn/autogradpp/test.cpp:523:48: note: construct_tests()::__lambda41
      auto& model, auto& forward_op, auto& optim) {
                                                ^
/home/d09/workspace/jjn/autogradpp/test.cpp:523:48: note:   candidate expects 3 arguments, 6 provided
/home/d09/workspace/jjn/autogradpp/test.cpp: In lambda function:
/home/d09/workspace/jjn/autogradpp/test.cpp:692:29: error: no match for call to ‘(const construct_tests()::__lambda41) (int, int, bool, std::shared_ptr<autograd::SimpleContainer>&, construct_tests()::__lambda46::__lambda47&, std::shared_ptr<autograd::SGD>&)’
        model, forward, optim);
                             ^
/home/d09/workspace/jjn/autogradpp/test.cpp:521:21: note: candidates are:
  auto test_mnist = [](
                     ^
/home/d09/workspace/jjn/autogradpp/test.cpp:692:29: note: void (*)(uint32_t, uint32_t, bool) {aka void (*)(unsigned int, unsigned int, bool)} <conversion>
        model, forward, optim);
                             ^
/home/d09/workspace/jjn/autogradpp/test.cpp:692:29: note:   candidate expects 4 arguments, 7 provided
/home/d09/workspace/jjn/autogradpp/test.cpp:523:48: note: construct_tests()::__lambda41
      auto& model, auto& forward_op, auto& optim) {
                                                ^
/home/d09/workspace/jjn/autogradpp/test.cpp:523:48: note:   candidate expects 3 arguments, 6 provided
make[2]: *** [CMakeFiles/autograd_test.dir/test.cpp.o] Error 1
make[1]: *** [CMakeFiles/autograd_test.dir/all] Error 2
make: *** [all] Error 2

Hey,when I build autogradpp "make -j",the error happend

**Comment by ebetica** [comment]
You might need a compiler with C++14 support

**Comment by jjn037** [comment]
I have updated my gcc version to 5.4.1, but another problems happend

/home/d09/workspace/jjn/autogradpp/autograd.cpp: In member function ‘virtual autograd::variable_list autograd::Embedding::forward(autograd::variable_list)’:
/home/d09/workspace/jjn/autogradpp/autograd.cpp:134:25: error: ‘embedding’ is not a member of ‘at’
   return variable_list({at::embedding(weight, x, -1, false, false)});
                         ^
/home/d09/workspace/jjn/autogradpp/autograd.cpp:134:68: error: no matching function for call to ‘std::vector<torch::autograd::Variable>::vector(<brace-enclosed initializer list>)’
   return variable_list({at::embedding(weight, x, -1, false, false)});
                                                                    ^
In file included from /usr/include/c++/5/vector:64:0,
                 from /home/d09/workspace/jjn/autogradpp/cereal/cereal.hpp:37,
                 from /home/d09/workspace/jjn/autogradpp/cereal/archives/binary.hpp:32,
                 from /home/d09/workspace/jjn/autogradpp/autograd.h:7,
                 from /home/d09/workspace/jjn/autogradpp/autograd.cpp:6:
/usr/include/c++/5/bits/stl_vector.h:401:9: note: candidate: template<class _InputIterator, class> std::vector<_Tp, _Alloc>::vector(_InputIterator, _InputIterator, const allocator_type&)
         vector(_InputIterator __first, _InputIterator __last,
         ^
/usr/include/c++/5/bits/stl_vector.h:401:9: note:   template argument deduction/substitution failed:
/home/d09/workspace/jjn/autogradpp/autograd.cpp:134:68: note:   candidate expects 3 arguments, 1 provided
   return variable_list({at::embedding(weight, x, -1, false, false)});
